### ISSUE TITLE
Font Awesome Icon Updates

### ISSUE THREAD

**Issue by sth3000** [JonMasterson/WordPress-Post-Like-System#10]
Hey Jon - great stuff here, thanks for sharing.  Quick but stupid question: how do I update the FA icon from a heart to a thumbs up (or any other FA icon)?  Thanks again!

**Comment by JonMasterson** [comment]
Hello,

This is pretty simple to update if your using the vendor/fontawesome version. All you'll need to do is find-and-replace the following in the .php and .js files:
- "fa-heart-o" with "fa-thumbs-o-up"
- "fa-heart" with "fa-thumbs-up"
