### ISSUE TITLE
Plugin crushes when non-admin user is pressing like

### ISSUE THREAD

**Issue by Ma3oBblu** [JonMasterson/WordPress-Post-Like-System#11]
Only with admin user it works perfect. Plz, help me to fix it. Is it only my problem? http://cpf.rusdigi.name/ here the like icon
http://cpf.rusdigi.name/login
test / test

**Comment by Ma3oBblu** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

have this warning in console

**Comment by ippopeya** [comment]
I've the same issue. Do you know the solution?

**Comment by JonMasterson** [comment]
Hello,

I was unable to duplicate your error. I noticed there were many scripts running on your site, and some additional errors, unrelated to this post like system. This could be part of the problem. [This thread](http://stackoverflow.com/questions/24639335/javascript-console-log-causes-error-synchronous-xmlhttprequest-on-the-main-thr) might help you solve the issue. Let me know how it works out. Thanks!

**Comment by Ma3oBblu** [comment]
i just rewrite your plugin for myself without extra functionality. Thanks for good ideas

**Comment by iosoft** [comment]
@Ma3oBblu, pls share your code.
