### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by shubhra14** [JonMasterson/WordPress-Post-Like-System#13]
There no issue here (yet!). I only logged in to say a big thank you for putting this out. Looking at all the help you have provided folks with different customizations, I want to say you are one of those rare selfless people who can go out of their way to help a person.

Thank you and stay like this!

**Comment by UnaiYecora** [comment]
+1

**Comment by JonMasterson** [comment]
This was nice to see. Thank you!
