### ISSUE TITLE
Inconsistent Functionality On A Clean WordPress Install

### ISSUE THREAD

**Issue by micahbolen** [JonMasterson/WordPress-Post-Like-System#14]
Hi Jon & Other Interested Parties (this means you),

I'm evaluating your awesome like system on a clean WordPress install using the stock Twenty Fifteen WP theme:

https://just-post-likes-micahbolen.c9.io/

I made 0 modifications to your code and 0 modifications to the stock WordPress code and I hope I followed your simple installation instructions adequately (pretty sure of this as I triple-checked).

I am seeing intermittent inconsistencies with the like count and intermittent unexpected behavior when the like button is pressed.  I want to say that the problems are more frequent when testing as an anonymous user, but I'm not certain if that's the only time I see the problems.

I'm not getting any JS or PHP errors.  Again, this is a clean WP install.  No other plugins and no obvious library conflicts or anything of that nature.

I'm reaching out to you (Jon in particular) primarily because I could not reproduce the problems I was seeing on my sandbox on your demo page: http://jonmasterson.com/post-like-demo/

It seems that your demo page runs just fine and I assume the related code on your demo page is pretty much identical to what is available in this repository.  However, I did notice that your demo page seems to take a little longer to process "likes" than my sandbox.  Ever so slightly longer.  Perhaps, it is because your demo page has lots of likes and, therefore, it takes longer to count them all.  That is what I assume.  So, that brings me back to my sandbox of a clean WP install.  

Any assistance or recommendations from anyone watching this repo would receive much kudos and praise for anything that is in the least bit helpful.

Kind Regards,

Micah

**Comment by JonMasterson** [comment]
Hi Micah,

I started working on an update to for this a few months back, but have not had a moment to get back to it yet. I will take a look and see if I can duplicate the issues you mentioned, using a fresh install with the the latest Github version. Thanks!

**Comment by micahbolen** [comment]
Hi Jon,

Let's work together on this.  What needs to be fixed and/or updated?  I know both front-end and back-end.  Just give me a clue what we need to look at together.  Feel free to PM me at micah dot bolen at gmail dot com.

Cheers,

Micah

**Comment by JonMasterson** [comment]
Hi Micah,

I was unable to duplicate your issue. I'm using a fresh install of WordPress, the TwentyFifteen theme, and the latest Github version of this post like system. 

I noticed that you renamed the javascript file, and that you are not using the minified version — which is a bit more that '0 modifications,' and deviates from the code I've offered here. You would need to make modifications in a few different files to accommodate the file name/reference difference you created. 

Please try again using a fresh download, and without modifying anything, and let me know if it works for you. Thanks!

**Comment by micahbolen** [comment]
OK, will let you know how it goes.

**Comment by JonMasterson** [comment]
Hi Micah,
Did it work? Let me know if I can close this issue. Thanks!

**Comment by micahbolen** [comment]
@JonMasterson The inconsistent functionality is not predictable on my end (whether I made any modifications or not), so go ahead and close this ticket.  

Yours is the best WordPress like system I have encountered so far.  It has everything I need and nothing I don't.  I've started my own separate attempt at an alternative solution relying more heavily on JavaScript, but have yet to incorporate it into the WordPress ecosystem.  Granted, I plan on merging my solution into WordPress this week.  Perhaps, when I am done with that, I can show you what I have come up with and we can compare notes.  Of course, only if you're interested.

**Comment by JonMasterson** [comment]
Sorry it's still not functioning for you — I am definitely interested in what you come up with. I have been refactoring this all into a plugin in my spare time — removing dependencies on jQuery/icon fonts in favor of vanilla javascript/svg with some admin management options/widgetized AJAX lists for most popular posts. It's still light on the front end, but is a lot more complex to enable easier management via the admin/AJAX updating of lists. Will roll all of this out in late August. This "no frills" non-plugin version will still be available on Github...
