### ISSUE TITLE
The like button didnt work outside for eample not in single page

### ISSUE THREAD

**Issue by anahitaida** [JonMasterson/WordPress-Post-Like-System#15]
I am displaying the post items and wanted to add the like button there also not only in single page and when putting it didnt work properly?Is it possible to fix?Thanks!

**Comment by shubhra14** [comment]
You can add this function `<?php getPostLikeLink( get_the_ID() ); ?>` in the loop. Replace get_the_ID() with howsoever you are getting the id. It should work.

**Comment by anahitaida** [comment]
I had done but not working, it shows correctly the count but when I click it didnt increase the count.How I can fix this?

**Comment by shubhra14** [comment]
Are there any jQuery errors? Did you change anything in the plugin?

**Comment by anahitaida** [comment]
No no errors and I didnt changed anything in the plugin

**Comment by anahitaida** [comment]
And when I click on like sometimes it increased, sometimes not and when I refresh the page it didnt save the count.

**Comment by JonMasterson** [comment]
Hi Anahitaida, Please give the latest version a try. Thanks!
