### ISSUE TITLE
May be a Security Issue

### ISSUE THREAD

**Issue by iosoft** [JonMasterson/WordPress-Post-Like-System#17]
Hello,

You have a very nice code, but I think there is one line that might be a Security Issue -
```
$is_comment = isset( $_REQUEST['is_comment'] ) ? $_REQUEST['is_comment'] : 0;
```
Might be used for Injection attack etc.

I would rather use -
```
$is_comment = isset( $_REQUEST['is_comment'] ) ? 1 : 0;
```

Just a suggestion.

**Comment by JonMasterson** [comment]
Oof. You are absolutely right. I will fix this oversight. Thank you.

**Comment by iosoft** [comment]
No problem. Glad to help you :)
