### ISSUE TITLE
make plugin available on wpackaginst as composer package

### ISSUE THREAD

**Issue by Qoto** [JonMasterson/WordPress-Post-Like-System#19]
Hi @JonMasterson 
thank you for developing this.
Is there a way for you to make plugin available on wpackaginst as composer package?

thanks

**Comment by JonMasterson** [comment]
Hi Daniel, I merged your pull request. I will be rolling out some bigger things for this in the coming weeks. A free plugin will be available from the WordPress SVN, so this will soon be available on WP Packagist. In addition, there will be two premium add-ons available for extending (admin post/user list sorting & AJAX widgets). Thank you!
