### ISSUE TITLE
Suggestion: Replace 'YourThemeTextDomain'

### ISSUE THREAD

**Issue by iosoft** [JonMasterson/WordPress-Post-Like-System#21]
Pls remove 'YourThemeTextDomain' with this following code block -

```php
$my_theme = wp_get_theme();
echo $my_theme->get( 'TextDomain' );
```

Ref: https://codex.wordpress.org/Function_Reference/wp_get_theme

**Comment by JonMasterson** [comment]
Don't believe this makes a huge difference, since it will have to be replaced on a theme-by-theme basis anyway, but will update on next commit. Thanks
