### ISSUE TITLE
Implementation outside of Wordpress? Complicated? or Not?

### ISSUE THREAD

**Issue by float-mode** [JonMasterson/WordPress-Post-Like-System#22]
I'm just wondering how hard would it be to modify this to work without wordpress. Non-programmer here, but I've seen PHP code around... I guess I'm just wondering if there is a point for me even starting it (like if it's too complex for php noop to comprehend), I mean I'm up for the challenge, I just don't know how tall of a mountain this would be for me. And if I should try and find something else already available? 

Any advice would be appreciated very much. 
Cheeers

**Comment by JonMasterson** [comment]
Hello, this is very integrated with WordPress. You'd have to replace all of the specific WordPress meta functions to update your DB.
