### ISSUE TITLE
Is it possible to add like and dislike button

### ISSUE THREAD

**Issue by rl421403** [JonMasterson/WordPress-Post-Like-System#3]
Hi,
I love this plugin. It's very easy to setup and minimal for what it does.
But I am in need to create 2 buttons for like and dislike. More like vote up and vote down button.
Can it be done with this plugin? Looking for a light weighted solution for this.

Please suggest.

**Comment by JonMasterson** [comment]
Haven't gotten around to this one yet, but will get to it soon...

**Comment by JonMasterson** [comment]
Decided not to add this functionality to this plugin.
