### ISSUE TITLE
Google Webmaster tools problem

### ISSUE THREAD

**Issue by fantastickmath** [JonMasterson/WordPress-Post-Like-System#30]
Hi there,

I have your plugin running on my website... it was all ok (I really liked it) but now when I access google webmaster tools It shows many software errors (google official link for tis error https://support.google.com/webmasters/answer/2409443?ctx=MCE&ctx=S4)... Now I have 491 software errors .... A usual link error seems like: 
http://www.website.com/wp-admin/admin-ajax.php?action=process_simple_like&nonce=e9509175b0&post_id=12121&disabled=true&is_comment=0

What this error mean? And how I can solve it?

Thanks

**Comment by JonMasterson** [comment]
Please see https://github.com/JonMasterson/WordPress-Post-Like-System/issues/27
