### ISSUE TITLE
Any chance it can work with ACF repeater and not wordpress loop?

### ISSUE THREAD

**Issue by hamergil** [JonMasterson/WordPress-Post-Like-System#55]
I'm using ACF repeater to display photos gallery.
obviously it doesn't work and change all photos when clicking on 1 photo.
is there any chance I can change something in the code and make it work with ACF repeater?

**Comment by carlbtmn** [comment]
Hello hamergil,

Were you able to figure this out? I know this thread is pretty old, but I'm also having issues using this system in a post query loop. If I like one post it affects all of them. I can't find a solution for this.

Thank you.
