### ISSUE TITLE
Is there a way I can manipulate the number of likes the heart displays or starts off?

### ISSUE THREAD

**Issue by BryanBarrera** [JonMasterson/WordPress-Post-Like-System#6]
Is there a way I can manipulate the number of likes the heart displays or starts off?

For example each post with the heart/like starts at 0 is there a way we can adjust the like number to start at like 25 or 213? 

Also is there a way the like/heart can have the letter 'k' after it reaches 1000 likes

For example 2,452 will translate to 2,45k or 2.4k 

Awesome plugin! Lightweight & simple to integrate.

**Comment by JonMasterson** [comment]
Hello,
You could update multiple posts via an SQL query in your database (this would add 25 likes to all posts):
```
INSERT INTO wp_postmeta (post_id, meta_key, meta_value)
SELECT ID AS post_id, '_post_like_count'
AS meta_key '25' AS meta_value FROM wp_posts
WHERE ID NOT IN (SELECT post_id FROM wp_postmeta WHERE meta_key = '_post_like_count');
```
You could also add 25 likes per individual posts with: 
```
update_post_meta( $post_id, "_post_like_count", 25 );
```

You could also instantly add 25 likes per post from the front end by changing the "jm_post_like()" function:
Everywhere you see...
```
update_post_meta( $post_id, "_post_like_count", ++$post_like_count );
```
Replace it with...
```
update_post_meta( $post_id, "_post_like_count", 25 );
```
You could then change it to varying numbers, and like certain posts to fake it until you make it. :+1: (Make sure to change it back to normal afterward if you want everything to work properly. Hope this helps!
