### ISSUE TITLE
Header plugin

### ISSUE THREAD

**Issue by eliasfaical** [JonMasterson/WordPress-Post-Like-System#7]
Hello JonMasterson, I'm using your plugin but I had to make a change in the header thus leaving.

Plugin Name: WordPress Post Like System
Plugin URI: http://jonmasterson.com/
Description: A simple and efficient post like system for WordPress.
Version: 4.0
Author: Jon Masterson
Author URI: http://boliquan.com/
Text Domain: WP-POST-LIKE
Domain Path: /lang

**Comment by JonMasterson** [comment]
This is AOK, man. Feel free to revise it as necessary. Thanks!
