### ISSUE TITLE
Possible to simply display total 'likes' of all posts of CPT?

### ISSUE THREAD

**Issue by JoshCarey** [JonMasterson/WordPress-Post-Like-System#9]
I've tried to manipulate a couple of the functions to get this solution, but I'm not having any luck.

Basically my client is asking that I have a display of all "likes" from the total of all the posts of this custom post type.  Its kind of a "here's how much activity this site is getting" kind of a statistic.

Is this possible?

**Comment by JonMasterson** [comment]
Hi Josh, Are you trying add together all likes from every post to get a total like count?

**Comment by JoshCarey** [comment]
Yes, sir - that's the goal.  Like: "look ALL of our posts have accumulated XXX number of likes".

**Comment by JonMasterson** [comment]
I believe this is what your after...
```
function jm_total_likes() {
	global $post;
	$combined = array();
	$args = array(
		 'post_type' => array( 'post', 'add_all_comma_separated_post_types_here' ),
		 'meta_query' => array(
			  array(
				  'key' => '_post_like_count',
				  'value' => '0',
				  'compare' => '>'
			  )
		  ),
		 'meta_key' => '_post_like_count',
		 'orderby' => 'meta_value_num',
		 'posts_per_page' => -1 
		 );
	$pop_posts = new WP_Query( $args );
	while ( $pop_posts->have_posts() ) {
		$pop_posts->the_post();
		$combined[] = get_post_meta( $post->ID, "_post_like_count", true );
	}
	wp_reset_postdata();
	echo "<h3>" . array_sum( $combined ) . " Likes</h3>\n";
}
```

**Comment by adeel000** [comment]
hy
 whats this?

**Comment by JonMasterson** [comment]
When configured with all of your site's post types, this function retrieves each post's _post_like_count, pushes each value to an array, adds all the values together, and outputs the total like count for your site.

**Comment by JoshCarey** [comment]
Hi, @JonMasterson  - I just wanted to chime back in here... I just got back to this project today and the function worked like a charm.  Thanks so much, I really appreciate it!  Great plugin :)
